//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCMI.TCMIContentServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prayer", Namespace="http://tcmicrossroadcontent.apphb.com/")]
    [System.SerializableAttribute()]
    public partial class Prayer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfidentialityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrayerRequestField;
        
        private System.DateTime ReceivedField;
        
        private int PrayedField;
        
        private bool AnsweredField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Confidentiality {
            get {
                return this.ConfidentialityField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfidentialityField, value) != true)) {
                    this.ConfidentialityField = value;
                    this.RaisePropertyChanged("Confidentiality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PrayerRequest {
            get {
                return this.PrayerRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.PrayerRequestField, value) != true)) {
                    this.PrayerRequestField = value;
                    this.RaisePropertyChanged("PrayerRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime Received {
            get {
                return this.ReceivedField;
            }
            set {
                if ((this.ReceivedField.Equals(value) != true)) {
                    this.ReceivedField = value;
                    this.RaisePropertyChanged("Received");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Prayed {
            get {
                return this.PrayedField;
            }
            set {
                if ((this.PrayedField.Equals(value) != true)) {
                    this.PrayedField = value;
                    this.RaisePropertyChanged("Prayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool Answered {
            get {
                return this.AnsweredField;
            }
            set {
                if ((this.AnsweredField.Equals(value) != true)) {
                    this.AnsweredField = value;
                    this.RaisePropertyChanged("Answered");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://tcmicrossroadcontent.apphb.com/")]
    [System.SerializableAttribute()]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueField;
        
        private System.DateTime DateOfEventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeField;
        
        private bool ExpiredField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Venue {
            get {
                return this.VenueField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueField, value) != true)) {
                    this.VenueField = value;
                    this.RaisePropertyChanged("Venue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime DateOfEvent {
            get {
                return this.DateOfEventField;
            }
            set {
                if ((this.DateOfEventField.Equals(value) != true)) {
                    this.DateOfEventField = value;
                    this.RaisePropertyChanged("DateOfEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Time {
            get {
                return this.TimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeField, value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool Expired {
            get {
                return this.ExpiredField;
            }
            set {
                if ((this.ExpiredField.Equals(value) != true)) {
                    this.ExpiredField = value;
                    this.RaisePropertyChanged("Expired");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/", ConfigurationName="TCMIContentServices.TCMIContentSoap")]
    public interface TCMIContentSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tcmicrossroadcontent.apphb.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/AddPrayer", ReplyAction="*")]
        TCMI.TCMIContentServices.AddPrayerResponse AddPrayer(TCMI.TCMIContentServices.AddPrayerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/AddPrayer", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.AddPrayerResponse> AddPrayerAsync(TCMI.TCMIContentServices.AddPrayerRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tcmicrossroadcontent.apphb.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/UpdatePrayer", ReplyAction="*")]
        TCMI.TCMIContentServices.UpdatePrayerResponse UpdatePrayer(TCMI.TCMIContentServices.UpdatePrayerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/UpdatePrayer", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.UpdatePrayerResponse> UpdatePrayerAsync(TCMI.TCMIContentServices.UpdatePrayerRequest request);
        
        // CODEGEN: Generating message contract since element name AnsweredPrayerResult from namespace http://tcmicrossroadcontent.apphb.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/AnsweredPrayer", ReplyAction="*")]
        TCMI.TCMIContentServices.AnsweredPrayerResponse AnsweredPrayer(TCMI.TCMIContentServices.AnsweredPrayerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/AnsweredPrayer", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.AnsweredPrayerResponse> AnsweredPrayerAsync(TCMI.TCMIContentServices.AnsweredPrayerRequest request);
        
        // CODEGEN: Generating message contract since element name PrayedResult from namespace http://tcmicrossroadcontent.apphb.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/Prayed", ReplyAction="*")]
        TCMI.TCMIContentServices.PrayedResponse Prayed(TCMI.TCMIContentServices.PrayedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/Prayed", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.PrayedResponse> PrayedAsync(TCMI.TCMIContentServices.PrayedRequest request);
        
        // CODEGEN: Generating message contract since element name GetPrayersResult from namespace http://tcmicrossroadcontent.apphb.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/GetPrayers", ReplyAction="*")]
        TCMI.TCMIContentServices.GetPrayersResponse GetPrayers(TCMI.TCMIContentServices.GetPrayersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/GetPrayers", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.GetPrayersResponse> GetPrayersAsync(TCMI.TCMIContentServices.GetPrayersRequest request);
        
        // CODEGEN: Generating message contract since element name RemovePrayerResult from namespace http://tcmicrossroadcontent.apphb.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/RemovePrayer", ReplyAction="*")]
        TCMI.TCMIContentServices.RemovePrayerResponse RemovePrayer(TCMI.TCMIContentServices.RemovePrayerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/RemovePrayer", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.RemovePrayerResponse> RemovePrayerAsync(TCMI.TCMIContentServices.RemovePrayerRequest request);
        
        // CODEGEN: Generating message contract since element name title from namespace http://tcmicrossroadcontent.apphb.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/AddEvent", ReplyAction="*")]
        TCMI.TCMIContentServices.AddEventResponse AddEvent(TCMI.TCMIContentServices.AddEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/AddEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.AddEventResponse> AddEventAsync(TCMI.TCMIContentServices.AddEventRequest request);
        
        // CODEGEN: Generating message contract since element name title from namespace http://tcmicrossroadcontent.apphb.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/UpdateEvent", ReplyAction="*")]
        TCMI.TCMIContentServices.UpdateEventResponse UpdateEvent(TCMI.TCMIContentServices.UpdateEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/UpdateEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.UpdateEventResponse> UpdateEventAsync(TCMI.TCMIContentServices.UpdateEventRequest request);
        
        // CODEGEN: Generating message contract since element name UpdateEventExpiredResult from namespace http://tcmicrossroadcontent.apphb.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/UpdateEventExpired", ReplyAction="*")]
        TCMI.TCMIContentServices.UpdateEventExpiredResponse UpdateEventExpired(TCMI.TCMIContentServices.UpdateEventExpiredRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/UpdateEventExpired", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.UpdateEventExpiredResponse> UpdateEventExpiredAsync(TCMI.TCMIContentServices.UpdateEventExpiredRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllEventsResult from namespace http://tcmicrossroadcontent.apphb.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/GetAllEvents", ReplyAction="*")]
        TCMI.TCMIContentServices.GetAllEventsResponse GetAllEvents(TCMI.TCMIContentServices.GetAllEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/GetAllEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.GetAllEventsResponse> GetAllEventsAsync(TCMI.TCMIContentServices.GetAllEventsRequest request);
        
        // CODEGEN: Generating message contract since element name GetActiveEventsResult from namespace http://tcmicrossroadcontent.apphb.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/GetActiveEvents", ReplyAction="*")]
        TCMI.TCMIContentServices.GetActiveEventsResponse GetActiveEvents(TCMI.TCMIContentServices.GetActiveEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/GetActiveEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.GetActiveEventsResponse> GetActiveEventsAsync(TCMI.TCMIContentServices.GetActiveEventsRequest request);
        
        // CODEGEN: Generating message contract since element name RemoveEventResult from namespace http://tcmicrossroadcontent.apphb.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/RemoveEvent", ReplyAction="*")]
        TCMI.TCMIContentServices.RemoveEventResponse RemoveEvent(TCMI.TCMIContentServices.RemoveEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/RemoveEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.RemoveEventResponse> RemoveEventAsync(TCMI.TCMIContentServices.RemoveEventRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPrayerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPrayer", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.AddPrayerRequestBody Body;
        
        public AddPrayerRequest() {
        }
        
        public AddPrayerRequest(TCMI.TCMIContentServices.AddPrayerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class AddPrayerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string confidential;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string request;
        
        public AddPrayerRequestBody() {
        }
        
        public AddPrayerRequestBody(string name, string email, string phone, string confidential, string request) {
            this.name = name;
            this.email = email;
            this.phone = phone;
            this.confidential = confidential;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPrayerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPrayerResponse", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.AddPrayerResponseBody Body;
        
        public AddPrayerResponse() {
        }
        
        public AddPrayerResponse(TCMI.TCMIContentServices.AddPrayerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class AddPrayerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddPrayerResult;
        
        public AddPrayerResponseBody() {
        }
        
        public AddPrayerResponseBody(string AddPrayerResult) {
            this.AddPrayerResult = AddPrayerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePrayerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePrayer", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.UpdatePrayerRequestBody Body;
        
        public UpdatePrayerRequest() {
        }
        
        public UpdatePrayerRequest(TCMI.TCMIContentServices.UpdatePrayerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class UpdatePrayerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string confidential;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string request;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int prayed;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool answered;
        
        public UpdatePrayerRequestBody() {
        }
        
        public UpdatePrayerRequestBody(int id, string name, string email, string phone, string confidential, string request, int prayed, bool answered) {
            this.id = id;
            this.name = name;
            this.email = email;
            this.phone = phone;
            this.confidential = confidential;
            this.request = request;
            this.prayed = prayed;
            this.answered = answered;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePrayerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePrayerResponse", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.UpdatePrayerResponseBody Body;
        
        public UpdatePrayerResponse() {
        }
        
        public UpdatePrayerResponse(TCMI.TCMIContentServices.UpdatePrayerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class UpdatePrayerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdatePrayerResult;
        
        public UpdatePrayerResponseBody() {
        }
        
        public UpdatePrayerResponseBody(string UpdatePrayerResult) {
            this.UpdatePrayerResult = UpdatePrayerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnsweredPrayerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnsweredPrayer", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.AnsweredPrayerRequestBody Body;
        
        public AnsweredPrayerRequest() {
        }
        
        public AnsweredPrayerRequest(TCMI.TCMIContentServices.AnsweredPrayerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class AnsweredPrayerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public AnsweredPrayerRequestBody() {
        }
        
        public AnsweredPrayerRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnsweredPrayerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnsweredPrayerResponse", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.AnsweredPrayerResponseBody Body;
        
        public AnsweredPrayerResponse() {
        }
        
        public AnsweredPrayerResponse(TCMI.TCMIContentServices.AnsweredPrayerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class AnsweredPrayerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AnsweredPrayerResult;
        
        public AnsweredPrayerResponseBody() {
        }
        
        public AnsweredPrayerResponseBody(string AnsweredPrayerResult) {
            this.AnsweredPrayerResult = AnsweredPrayerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrayedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Prayed", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.PrayedRequestBody Body;
        
        public PrayedRequest() {
        }
        
        public PrayedRequest(TCMI.TCMIContentServices.PrayedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class PrayedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public PrayedRequestBody() {
        }
        
        public PrayedRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrayedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrayedResponse", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.PrayedResponseBody Body;
        
        public PrayedResponse() {
        }
        
        public PrayedResponse(TCMI.TCMIContentServices.PrayedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class PrayedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrayedResult;
        
        public PrayedResponseBody() {
        }
        
        public PrayedResponseBody(string PrayedResult) {
            this.PrayedResult = PrayedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPrayersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPrayers", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.GetPrayersRequestBody Body;
        
        public GetPrayersRequest() {
        }
        
        public GetPrayersRequest(TCMI.TCMIContentServices.GetPrayersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPrayersRequestBody {
        
        public GetPrayersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPrayersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPrayersResponse", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.GetPrayersResponseBody Body;
        
        public GetPrayersResponse() {
        }
        
        public GetPrayersResponse(TCMI.TCMIContentServices.GetPrayersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class GetPrayersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TCMI.TCMIContentServices.Prayer[] GetPrayersResult;
        
        public GetPrayersResponseBody() {
        }
        
        public GetPrayersResponseBody(TCMI.TCMIContentServices.Prayer[] GetPrayersResult) {
            this.GetPrayersResult = GetPrayersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemovePrayerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemovePrayer", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.RemovePrayerRequestBody Body;
        
        public RemovePrayerRequest() {
        }
        
        public RemovePrayerRequest(TCMI.TCMIContentServices.RemovePrayerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class RemovePrayerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public RemovePrayerRequestBody() {
        }
        
        public RemovePrayerRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemovePrayerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemovePrayerResponse", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.RemovePrayerResponseBody Body;
        
        public RemovePrayerResponse() {
        }
        
        public RemovePrayerResponse(TCMI.TCMIContentServices.RemovePrayerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class RemovePrayerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RemovePrayerResult;
        
        public RemovePrayerResponseBody() {
        }
        
        public RemovePrayerResponseBody(string RemovePrayerResult) {
            this.RemovePrayerResult = RemovePrayerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEvent", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.AddEventRequestBody Body;
        
        public AddEventRequest() {
        }
        
        public AddEventRequest(TCMI.TCMIContentServices.AddEventRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class AddEventRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string desc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string time;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string venue;
        
        public AddEventRequestBody() {
        }
        
        public AddEventRequestBody(string title, string desc, System.DateTime date, string time, string venue) {
            this.title = title;
            this.desc = desc;
            this.date = date;
            this.time = time;
            this.venue = venue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEventResponse", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.AddEventResponseBody Body;
        
        public AddEventResponse() {
        }
        
        public AddEventResponse(TCMI.TCMIContentServices.AddEventResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class AddEventResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddEventResult;
        
        public AddEventResponseBody() {
        }
        
        public AddEventResponseBody(string AddEventResult) {
            this.AddEventResult = AddEventResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEvent", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.UpdateEventRequestBody Body;
        
        public UpdateEventRequest() {
        }
        
        public UpdateEventRequest(TCMI.TCMIContentServices.UpdateEventRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class UpdateEventRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string desc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string time;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string venue;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool isexpired;
        
        public UpdateEventRequestBody() {
        }
        
        public UpdateEventRequestBody(int id, string title, string desc, System.DateTime date, string time, string venue, bool isexpired) {
            this.id = id;
            this.title = title;
            this.desc = desc;
            this.date = date;
            this.time = time;
            this.venue = venue;
            this.isexpired = isexpired;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEventResponse", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.UpdateEventResponseBody Body;
        
        public UpdateEventResponse() {
        }
        
        public UpdateEventResponse(TCMI.TCMIContentServices.UpdateEventResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class UpdateEventResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateEventResult;
        
        public UpdateEventResponseBody() {
        }
        
        public UpdateEventResponseBody(string UpdateEventResult) {
            this.UpdateEventResult = UpdateEventResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEventExpiredRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEventExpired", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.UpdateEventExpiredRequestBody Body;
        
        public UpdateEventExpiredRequest() {
        }
        
        public UpdateEventExpiredRequest(TCMI.TCMIContentServices.UpdateEventExpiredRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class UpdateEventExpiredRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public UpdateEventExpiredRequestBody() {
        }
        
        public UpdateEventExpiredRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEventExpiredResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEventExpiredResponse", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.UpdateEventExpiredResponseBody Body;
        
        public UpdateEventExpiredResponse() {
        }
        
        public UpdateEventExpiredResponse(TCMI.TCMIContentServices.UpdateEventExpiredResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class UpdateEventExpiredResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateEventExpiredResult;
        
        public UpdateEventExpiredResponseBody() {
        }
        
        public UpdateEventExpiredResponseBody(string UpdateEventExpiredResult) {
            this.UpdateEventExpiredResult = UpdateEventExpiredResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllEventsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllEvents", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.GetAllEventsRequestBody Body;
        
        public GetAllEventsRequest() {
        }
        
        public GetAllEventsRequest(TCMI.TCMIContentServices.GetAllEventsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllEventsRequestBody {
        
        public GetAllEventsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllEventsResponse", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.GetAllEventsResponseBody Body;
        
        public GetAllEventsResponse() {
        }
        
        public GetAllEventsResponse(TCMI.TCMIContentServices.GetAllEventsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class GetAllEventsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TCMI.TCMIContentServices.Event[] GetAllEventsResult;
        
        public GetAllEventsResponseBody() {
        }
        
        public GetAllEventsResponseBody(TCMI.TCMIContentServices.Event[] GetAllEventsResult) {
            this.GetAllEventsResult = GetAllEventsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActiveEventsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActiveEvents", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.GetActiveEventsRequestBody Body;
        
        public GetActiveEventsRequest() {
        }
        
        public GetActiveEventsRequest(TCMI.TCMIContentServices.GetActiveEventsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetActiveEventsRequestBody {
        
        public GetActiveEventsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActiveEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActiveEventsResponse", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.GetActiveEventsResponseBody Body;
        
        public GetActiveEventsResponse() {
        }
        
        public GetActiveEventsResponse(TCMI.TCMIContentServices.GetActiveEventsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class GetActiveEventsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TCMI.TCMIContentServices.Event[] GetActiveEventsResult;
        
        public GetActiveEventsResponseBody() {
        }
        
        public GetActiveEventsResponseBody(TCMI.TCMIContentServices.Event[] GetActiveEventsResult) {
            this.GetActiveEventsResult = GetActiveEventsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveEvent", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.RemoveEventRequestBody Body;
        
        public RemoveEventRequest() {
        }
        
        public RemoveEventRequest(TCMI.TCMIContentServices.RemoveEventRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class RemoveEventRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public RemoveEventRequestBody() {
        }
        
        public RemoveEventRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveEventResponse", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMI.TCMIContentServices.RemoveEventResponseBody Body;
        
        public RemoveEventResponse() {
        }
        
        public RemoveEventResponse(TCMI.TCMIContentServices.RemoveEventResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class RemoveEventResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RemoveEventResult;
        
        public RemoveEventResponseBody() {
        }
        
        public RemoveEventResponseBody(string RemoveEventResult) {
            this.RemoveEventResult = RemoveEventResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TCMIContentSoapChannel : TCMI.TCMIContentServices.TCMIContentSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TCMIContentSoapClient : System.ServiceModel.ClientBase<TCMI.TCMIContentServices.TCMIContentSoap>, TCMI.TCMIContentServices.TCMIContentSoap {
        
        public TCMIContentSoapClient() {
        }
        
        public TCMIContentSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TCMIContentSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCMIContentSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCMIContentSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMI.TCMIContentServices.AddPrayerResponse TCMI.TCMIContentServices.TCMIContentSoap.AddPrayer(TCMI.TCMIContentServices.AddPrayerRequest request) {
            return base.Channel.AddPrayer(request);
        }
        
        public string AddPrayer(string name, string email, string phone, string confidential, string request) {
            TCMI.TCMIContentServices.AddPrayerRequest inValue = new TCMI.TCMIContentServices.AddPrayerRequest();
            inValue.Body = new TCMI.TCMIContentServices.AddPrayerRequestBody();
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.phone = phone;
            inValue.Body.confidential = confidential;
            inValue.Body.request = request;
            TCMI.TCMIContentServices.AddPrayerResponse retVal = ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).AddPrayer(inValue);
            return retVal.Body.AddPrayerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.AddPrayerResponse> TCMI.TCMIContentServices.TCMIContentSoap.AddPrayerAsync(TCMI.TCMIContentServices.AddPrayerRequest request) {
            return base.Channel.AddPrayerAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCMI.TCMIContentServices.AddPrayerResponse> AddPrayerAsync(string name, string email, string phone, string confidential, string request) {
            TCMI.TCMIContentServices.AddPrayerRequest inValue = new TCMI.TCMIContentServices.AddPrayerRequest();
            inValue.Body = new TCMI.TCMIContentServices.AddPrayerRequestBody();
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.phone = phone;
            inValue.Body.confidential = confidential;
            inValue.Body.request = request;
            return ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).AddPrayerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMI.TCMIContentServices.UpdatePrayerResponse TCMI.TCMIContentServices.TCMIContentSoap.UpdatePrayer(TCMI.TCMIContentServices.UpdatePrayerRequest request) {
            return base.Channel.UpdatePrayer(request);
        }
        
        public string UpdatePrayer(int id, string name, string email, string phone, string confidential, string request, int prayed, bool answered) {
            TCMI.TCMIContentServices.UpdatePrayerRequest inValue = new TCMI.TCMIContentServices.UpdatePrayerRequest();
            inValue.Body = new TCMI.TCMIContentServices.UpdatePrayerRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.phone = phone;
            inValue.Body.confidential = confidential;
            inValue.Body.request = request;
            inValue.Body.prayed = prayed;
            inValue.Body.answered = answered;
            TCMI.TCMIContentServices.UpdatePrayerResponse retVal = ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).UpdatePrayer(inValue);
            return retVal.Body.UpdatePrayerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.UpdatePrayerResponse> TCMI.TCMIContentServices.TCMIContentSoap.UpdatePrayerAsync(TCMI.TCMIContentServices.UpdatePrayerRequest request) {
            return base.Channel.UpdatePrayerAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCMI.TCMIContentServices.UpdatePrayerResponse> UpdatePrayerAsync(int id, string name, string email, string phone, string confidential, string request, int prayed, bool answered) {
            TCMI.TCMIContentServices.UpdatePrayerRequest inValue = new TCMI.TCMIContentServices.UpdatePrayerRequest();
            inValue.Body = new TCMI.TCMIContentServices.UpdatePrayerRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.phone = phone;
            inValue.Body.confidential = confidential;
            inValue.Body.request = request;
            inValue.Body.prayed = prayed;
            inValue.Body.answered = answered;
            return ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).UpdatePrayerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMI.TCMIContentServices.AnsweredPrayerResponse TCMI.TCMIContentServices.TCMIContentSoap.AnsweredPrayer(TCMI.TCMIContentServices.AnsweredPrayerRequest request) {
            return base.Channel.AnsweredPrayer(request);
        }
        
        public string AnsweredPrayer(int id) {
            TCMI.TCMIContentServices.AnsweredPrayerRequest inValue = new TCMI.TCMIContentServices.AnsweredPrayerRequest();
            inValue.Body = new TCMI.TCMIContentServices.AnsweredPrayerRequestBody();
            inValue.Body.id = id;
            TCMI.TCMIContentServices.AnsweredPrayerResponse retVal = ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).AnsweredPrayer(inValue);
            return retVal.Body.AnsweredPrayerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.AnsweredPrayerResponse> TCMI.TCMIContentServices.TCMIContentSoap.AnsweredPrayerAsync(TCMI.TCMIContentServices.AnsweredPrayerRequest request) {
            return base.Channel.AnsweredPrayerAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCMI.TCMIContentServices.AnsweredPrayerResponse> AnsweredPrayerAsync(int id) {
            TCMI.TCMIContentServices.AnsweredPrayerRequest inValue = new TCMI.TCMIContentServices.AnsweredPrayerRequest();
            inValue.Body = new TCMI.TCMIContentServices.AnsweredPrayerRequestBody();
            inValue.Body.id = id;
            return ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).AnsweredPrayerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMI.TCMIContentServices.PrayedResponse TCMI.TCMIContentServices.TCMIContentSoap.Prayed(TCMI.TCMIContentServices.PrayedRequest request) {
            return base.Channel.Prayed(request);
        }
        
        public string Prayed(int id) {
            TCMI.TCMIContentServices.PrayedRequest inValue = new TCMI.TCMIContentServices.PrayedRequest();
            inValue.Body = new TCMI.TCMIContentServices.PrayedRequestBody();
            inValue.Body.id = id;
            TCMI.TCMIContentServices.PrayedResponse retVal = ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).Prayed(inValue);
            return retVal.Body.PrayedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.PrayedResponse> TCMI.TCMIContentServices.TCMIContentSoap.PrayedAsync(TCMI.TCMIContentServices.PrayedRequest request) {
            return base.Channel.PrayedAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCMI.TCMIContentServices.PrayedResponse> PrayedAsync(int id) {
            TCMI.TCMIContentServices.PrayedRequest inValue = new TCMI.TCMIContentServices.PrayedRequest();
            inValue.Body = new TCMI.TCMIContentServices.PrayedRequestBody();
            inValue.Body.id = id;
            return ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).PrayedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMI.TCMIContentServices.GetPrayersResponse TCMI.TCMIContentServices.TCMIContentSoap.GetPrayers(TCMI.TCMIContentServices.GetPrayersRequest request) {
            return base.Channel.GetPrayers(request);
        }
        
        public TCMI.TCMIContentServices.Prayer[] GetPrayers() {
            TCMI.TCMIContentServices.GetPrayersRequest inValue = new TCMI.TCMIContentServices.GetPrayersRequest();
            inValue.Body = new TCMI.TCMIContentServices.GetPrayersRequestBody();
            TCMI.TCMIContentServices.GetPrayersResponse retVal = ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).GetPrayers(inValue);
            return retVal.Body.GetPrayersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.GetPrayersResponse> TCMI.TCMIContentServices.TCMIContentSoap.GetPrayersAsync(TCMI.TCMIContentServices.GetPrayersRequest request) {
            return base.Channel.GetPrayersAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCMI.TCMIContentServices.GetPrayersResponse> GetPrayersAsync() {
            TCMI.TCMIContentServices.GetPrayersRequest inValue = new TCMI.TCMIContentServices.GetPrayersRequest();
            inValue.Body = new TCMI.TCMIContentServices.GetPrayersRequestBody();
            return ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).GetPrayersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMI.TCMIContentServices.RemovePrayerResponse TCMI.TCMIContentServices.TCMIContentSoap.RemovePrayer(TCMI.TCMIContentServices.RemovePrayerRequest request) {
            return base.Channel.RemovePrayer(request);
        }
        
        public string RemovePrayer(int id) {
            TCMI.TCMIContentServices.RemovePrayerRequest inValue = new TCMI.TCMIContentServices.RemovePrayerRequest();
            inValue.Body = new TCMI.TCMIContentServices.RemovePrayerRequestBody();
            inValue.Body.id = id;
            TCMI.TCMIContentServices.RemovePrayerResponse retVal = ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).RemovePrayer(inValue);
            return retVal.Body.RemovePrayerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.RemovePrayerResponse> TCMI.TCMIContentServices.TCMIContentSoap.RemovePrayerAsync(TCMI.TCMIContentServices.RemovePrayerRequest request) {
            return base.Channel.RemovePrayerAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCMI.TCMIContentServices.RemovePrayerResponse> RemovePrayerAsync(int id) {
            TCMI.TCMIContentServices.RemovePrayerRequest inValue = new TCMI.TCMIContentServices.RemovePrayerRequest();
            inValue.Body = new TCMI.TCMIContentServices.RemovePrayerRequestBody();
            inValue.Body.id = id;
            return ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).RemovePrayerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMI.TCMIContentServices.AddEventResponse TCMI.TCMIContentServices.TCMIContentSoap.AddEvent(TCMI.TCMIContentServices.AddEventRequest request) {
            return base.Channel.AddEvent(request);
        }
        
        public string AddEvent(string title, string desc, System.DateTime date, string time, string venue) {
            TCMI.TCMIContentServices.AddEventRequest inValue = new TCMI.TCMIContentServices.AddEventRequest();
            inValue.Body = new TCMI.TCMIContentServices.AddEventRequestBody();
            inValue.Body.title = title;
            inValue.Body.desc = desc;
            inValue.Body.date = date;
            inValue.Body.time = time;
            inValue.Body.venue = venue;
            TCMI.TCMIContentServices.AddEventResponse retVal = ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).AddEvent(inValue);
            return retVal.Body.AddEventResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.AddEventResponse> TCMI.TCMIContentServices.TCMIContentSoap.AddEventAsync(TCMI.TCMIContentServices.AddEventRequest request) {
            return base.Channel.AddEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCMI.TCMIContentServices.AddEventResponse> AddEventAsync(string title, string desc, System.DateTime date, string time, string venue) {
            TCMI.TCMIContentServices.AddEventRequest inValue = new TCMI.TCMIContentServices.AddEventRequest();
            inValue.Body = new TCMI.TCMIContentServices.AddEventRequestBody();
            inValue.Body.title = title;
            inValue.Body.desc = desc;
            inValue.Body.date = date;
            inValue.Body.time = time;
            inValue.Body.venue = venue;
            return ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).AddEventAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMI.TCMIContentServices.UpdateEventResponse TCMI.TCMIContentServices.TCMIContentSoap.UpdateEvent(TCMI.TCMIContentServices.UpdateEventRequest request) {
            return base.Channel.UpdateEvent(request);
        }
        
        public string UpdateEvent(int id, string title, string desc, System.DateTime date, string time, string venue, bool isexpired) {
            TCMI.TCMIContentServices.UpdateEventRequest inValue = new TCMI.TCMIContentServices.UpdateEventRequest();
            inValue.Body = new TCMI.TCMIContentServices.UpdateEventRequestBody();
            inValue.Body.id = id;
            inValue.Body.title = title;
            inValue.Body.desc = desc;
            inValue.Body.date = date;
            inValue.Body.time = time;
            inValue.Body.venue = venue;
            inValue.Body.isexpired = isexpired;
            TCMI.TCMIContentServices.UpdateEventResponse retVal = ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).UpdateEvent(inValue);
            return retVal.Body.UpdateEventResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.UpdateEventResponse> TCMI.TCMIContentServices.TCMIContentSoap.UpdateEventAsync(TCMI.TCMIContentServices.UpdateEventRequest request) {
            return base.Channel.UpdateEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCMI.TCMIContentServices.UpdateEventResponse> UpdateEventAsync(int id, string title, string desc, System.DateTime date, string time, string venue, bool isexpired) {
            TCMI.TCMIContentServices.UpdateEventRequest inValue = new TCMI.TCMIContentServices.UpdateEventRequest();
            inValue.Body = new TCMI.TCMIContentServices.UpdateEventRequestBody();
            inValue.Body.id = id;
            inValue.Body.title = title;
            inValue.Body.desc = desc;
            inValue.Body.date = date;
            inValue.Body.time = time;
            inValue.Body.venue = venue;
            inValue.Body.isexpired = isexpired;
            return ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).UpdateEventAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMI.TCMIContentServices.UpdateEventExpiredResponse TCMI.TCMIContentServices.TCMIContentSoap.UpdateEventExpired(TCMI.TCMIContentServices.UpdateEventExpiredRequest request) {
            return base.Channel.UpdateEventExpired(request);
        }
        
        public string UpdateEventExpired(int id) {
            TCMI.TCMIContentServices.UpdateEventExpiredRequest inValue = new TCMI.TCMIContentServices.UpdateEventExpiredRequest();
            inValue.Body = new TCMI.TCMIContentServices.UpdateEventExpiredRequestBody();
            inValue.Body.id = id;
            TCMI.TCMIContentServices.UpdateEventExpiredResponse retVal = ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).UpdateEventExpired(inValue);
            return retVal.Body.UpdateEventExpiredResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.UpdateEventExpiredResponse> TCMI.TCMIContentServices.TCMIContentSoap.UpdateEventExpiredAsync(TCMI.TCMIContentServices.UpdateEventExpiredRequest request) {
            return base.Channel.UpdateEventExpiredAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCMI.TCMIContentServices.UpdateEventExpiredResponse> UpdateEventExpiredAsync(int id) {
            TCMI.TCMIContentServices.UpdateEventExpiredRequest inValue = new TCMI.TCMIContentServices.UpdateEventExpiredRequest();
            inValue.Body = new TCMI.TCMIContentServices.UpdateEventExpiredRequestBody();
            inValue.Body.id = id;
            return ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).UpdateEventExpiredAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMI.TCMIContentServices.GetAllEventsResponse TCMI.TCMIContentServices.TCMIContentSoap.GetAllEvents(TCMI.TCMIContentServices.GetAllEventsRequest request) {
            return base.Channel.GetAllEvents(request);
        }
        
        public TCMI.TCMIContentServices.Event[] GetAllEvents() {
            TCMI.TCMIContentServices.GetAllEventsRequest inValue = new TCMI.TCMIContentServices.GetAllEventsRequest();
            inValue.Body = new TCMI.TCMIContentServices.GetAllEventsRequestBody();
            TCMI.TCMIContentServices.GetAllEventsResponse retVal = ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).GetAllEvents(inValue);
            return retVal.Body.GetAllEventsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.GetAllEventsResponse> TCMI.TCMIContentServices.TCMIContentSoap.GetAllEventsAsync(TCMI.TCMIContentServices.GetAllEventsRequest request) {
            return base.Channel.GetAllEventsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCMI.TCMIContentServices.GetAllEventsResponse> GetAllEventsAsync() {
            TCMI.TCMIContentServices.GetAllEventsRequest inValue = new TCMI.TCMIContentServices.GetAllEventsRequest();
            inValue.Body = new TCMI.TCMIContentServices.GetAllEventsRequestBody();
            return ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).GetAllEventsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMI.TCMIContentServices.GetActiveEventsResponse TCMI.TCMIContentServices.TCMIContentSoap.GetActiveEvents(TCMI.TCMIContentServices.GetActiveEventsRequest request) {
            return base.Channel.GetActiveEvents(request);
        }
        
        public TCMI.TCMIContentServices.Event[] GetActiveEvents() {
            TCMI.TCMIContentServices.GetActiveEventsRequest inValue = new TCMI.TCMIContentServices.GetActiveEventsRequest();
            inValue.Body = new TCMI.TCMIContentServices.GetActiveEventsRequestBody();
            TCMI.TCMIContentServices.GetActiveEventsResponse retVal = ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).GetActiveEvents(inValue);
            return retVal.Body.GetActiveEventsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.GetActiveEventsResponse> TCMI.TCMIContentServices.TCMIContentSoap.GetActiveEventsAsync(TCMI.TCMIContentServices.GetActiveEventsRequest request) {
            return base.Channel.GetActiveEventsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCMI.TCMIContentServices.GetActiveEventsResponse> GetActiveEventsAsync() {
            TCMI.TCMIContentServices.GetActiveEventsRequest inValue = new TCMI.TCMIContentServices.GetActiveEventsRequest();
            inValue.Body = new TCMI.TCMIContentServices.GetActiveEventsRequestBody();
            return ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).GetActiveEventsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMI.TCMIContentServices.RemoveEventResponse TCMI.TCMIContentServices.TCMIContentSoap.RemoveEvent(TCMI.TCMIContentServices.RemoveEventRequest request) {
            return base.Channel.RemoveEvent(request);
        }
        
        public string RemoveEvent(int id) {
            TCMI.TCMIContentServices.RemoveEventRequest inValue = new TCMI.TCMIContentServices.RemoveEventRequest();
            inValue.Body = new TCMI.TCMIContentServices.RemoveEventRequestBody();
            inValue.Body.id = id;
            TCMI.TCMIContentServices.RemoveEventResponse retVal = ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).RemoveEvent(inValue);
            return retVal.Body.RemoveEventResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMI.TCMIContentServices.RemoveEventResponse> TCMI.TCMIContentServices.TCMIContentSoap.RemoveEventAsync(TCMI.TCMIContentServices.RemoveEventRequest request) {
            return base.Channel.RemoveEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCMI.TCMIContentServices.RemoveEventResponse> RemoveEventAsync(int id) {
            TCMI.TCMIContentServices.RemoveEventRequest inValue = new TCMI.TCMIContentServices.RemoveEventRequest();
            inValue.Body = new TCMI.TCMIContentServices.RemoveEventRequestBody();
            inValue.Body.id = id;
            return ((TCMI.TCMIContentServices.TCMIContentSoap)(this)).RemoveEventAsync(inValue);
        }
    }
}
